name = "Hyas"
license = "MIT"
licenselink = "https://github.com/h-enk/hyas/blob/master/LICENSE"
description = "Hugo starter helping you build modern websites that are secure, fast, and SEO-ready — by default."
homepage = "https://gethyas.com/"
tags = ["landing page", "blog", "minimal", "modern", "customizable"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "netlify-ready"]
min_version = "0.75.0"

[author]
  name = "Henk Verlinde"
  homepage = "https://henkverlinde.com/"
